# permissions for end users to edit yanetconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: yanetconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: yanet-operator
    app.kubernetes.io/part-of: yanet-operator
    app.kubernetes.io/managed-by: kustomize
  name: yanetconfig-editor-role
rules:
- apiGroups:
  - yanet.yanet-platform.io
  resources:
  - yanetconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yanet.yanet-platform.io
  resources:
  - yanetconfigs/status
  verbs:
  - get
